// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-tour-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tour-data.ts
var tourData = {
  id: "SUB-5D4N-001",
  title: "Leisurely Java Nature Trip: 5D 4N Surabaya - Mount Ijen - Papuma Beach - Tumpak Sewu Waterfall - Mount Bromo",
  location: "East Java, Indonesia",
  duration: "5 days, 4 nights",
  groupSize: "1-15+ people",
  languages: ["English"],
  rating: 4.6,
  reviewCount: 127,
  operatorName: "Java Volcano Tour Operator",
  currency: "IDR",
  basePrice: 365e4,
  description: "A 5-day East Java adventure covering Mount Ijen's blue fire, Papuma Beach, Tumpak Sewu Waterfall, and Mount Bromo sunrise. Includes private transport, English-speaking guides, hotel accommodation, and most meals.",
  highlights: [
    "Iconic sunrise viewpoint and hike to Bromo crater across sea of sand",
    "Scenic white-sand beach, dramatic rocks, sunrise/sunset spot",
    "Spectacular tiered waterfall with a trek to the base and panoramic view",
    "Witness rare blue flames at Ijen Crater",
    "Enjoy comfortable accommodations",
    "Benefit from private transportation",
    "Guided by experienced English-speaking guides"
  ],
  pricingTiers: [
    { groupSize: "Solo Traveler", pricePerPerson: 905e4 },
    { groupSize: "2 Pax", pricePerPerson: 505e4 },
    { groupSize: "3 Pax", pricePerPerson: 485e4 },
    { groupSize: "4 - 5 Pax", pricePerPerson: 455e4 },
    { groupSize: "6 - 7 Pax", pricePerPerson: 425e4 },
    { groupSize: "8 - 10 Pax", pricePerPerson: 385e4 },
    { groupSize: "11 + Pax", pricePerPerson: 365e4 }
  ],
  included: [
    "Private Transport: Air-conditioned private vehicles with a dedicated driver",
    "Tour Guides: Experienced English-speaking guides",
    "Mineral Water: Daily supply",
    "Complimentary Travel T-Shirt: One custom travel T-shirt per participant",
    "Quality Hotel Accommodation: For 4 nights, including daily breakfast",
    "All Entrance Fees & Permits to Mount Ijen, Papuma Beach, Tumpak Sewu Waterfall, Mount Bromo",
    "Meals: 4x Breakfast, 2x Lunch, 1x Dinner",
    "Private 4WD Jeep for the Mount Bromo sunrise tour",
    "Medical Check-up required by Ijen authorities, arranged at your hotel",
    "Trekking Equipment: Gas masks and trekking poles for Ijen, headlamps for night hikes"
  ],
  notIncluded: [
    "International/Domestic Air Tickets",
    "Indonesian VISA (if applicable)",
    "Travel Insurance (optional but recommended)",
    "Meals not stated in itinerary",
    "Personal Expenses (snacks, souvenirs, beverages, laundry)",
    "Tips for drivers and guides",
    "Optional Activities: Horse ride at Mount Bromo, Ijen Ojek Trolley Service"
  ],
  itinerary: [
    {
      day: 1,
      title: "Arrival in Surabaya and Journey to Bondowoso",
      accommodation: "Riverside Homestay - Bondowoso City",
      meals: "Dinner"
    },
    {
      day: 2,
      title: "Ijen Crater Adventure and Papuma Beach Sunset",
      accommodation: "Doho Homestay - Jember City",
      meals: "Breakfast, Lunch"
    },
    {
      day: 3,
      title: "Tumpak Sewu Waterfall and Journey to Bromo",
      accommodation: "Joglo Kecombrang Bromo - Bromo Area",
      meals: "Breakfast, Lunch"
    },
    {
      day: 4,
      title: "Bromo Sunrise Adventure and Return to Surabaya",
      accommodation: "Holiday Inn Express Surabaya Centerpoint",
      meals: "Breakfast"
    },
    {
      day: 5,
      title: "Departure from Surabaya",
      accommodation: null,
      meals: "Breakfast"
    }
  ],
  faq: [
    { q: "What kind of tours do you offer?", a: "All tour packages are private and all-inclusive." },
    { q: "Can I customize my tour?", a: "Yes, minor adjustments are allowed; major detours are discouraged." },
    { q: "How do I confirm my booking?", a: "A 20% deposit confirms the booking; the balance is due 3 days before departure." },
    { q: "What payment methods are accepted?", a: "Cash, bank transfer, major credit cards, and Wise." },
    { q: "What happens if the weather is bad?", a: "Itineraries may be adjusted for safety in extreme weather; light rain tours continue." },
    { q: "Is this tour suitable for children or elderly people?", a: "It requires good physical fitness; early starts and hiking are involved." },
    { q: "Do you cater to dietary restrictions?", a: "Yes \u2014 vegetarian, vegan, halal, and basic allergies can be accommodated." },
    { q: "What languages do the guides speak?", a: "All guides speak English fluently." },
    { q: "What is your safety record?", a: "100% safety record with local, dedicated crew." }
  ]
};
function priceForTravelers(travelers) {
  const t = tourData.pricingTiers;
  if (travelers <= 1) return t[0];
  if (travelers === 2) return t[1];
  if (travelers === 3) return t[2];
  if (travelers <= 5) return t[3];
  if (travelers <= 7) return t[4];
  if (travelers <= 10) return t[5];
  return t[6];
}

// src/lib/mcp/tools/get-tour-overview.ts
var get_tour_overview_default = defineTool({
  name: "get_tour_overview",
  title: "Get tour overview",
  description: "Return the East Java 5D4N tour overview: title, location, duration, rating, operator, currency, base price, and highlights.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const overview = {
      id: tourData.id,
      title: tourData.title,
      location: tourData.location,
      duration: tourData.duration,
      groupSize: tourData.groupSize,
      languages: tourData.languages,
      rating: tourData.rating,
      reviewCount: tourData.reviewCount,
      operatorName: tourData.operatorName,
      currency: tourData.currency,
      basePricePerPerson: tourData.basePrice,
      description: tourData.description,
      highlights: tourData.highlights
    };
    return {
      content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
      structuredContent: overview
    };
  }
});

// src/lib/mcp/tools/get-itinerary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_itinerary_default = defineTool2({
  name: "get_itinerary",
  title: "Get tour itinerary",
  description: "Return the day-by-day itinerary for the East Java 5D4N tour.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const itinerary = tourData.itinerary;
    return {
      content: [{ type: "text", text: JSON.stringify(itinerary, null, 2) }],
      structuredContent: { itinerary }
    };
  }
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.23.8";
var get_pricing_default = defineTool3({
  name: "get_pricing",
  title: "Get tour pricing",
  description: "Return the full per-person pricing tier table for the East Java 5D4N tour, and optionally quote a price for a specific group size.",
  inputSchema: {
    travelers: z.number().int().min(1).max(50).optional().describe("Optional group size. If provided, also returns the matching tier and total price.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ travelers }) => {
    const result = {
      currency: tourData.currency,
      tiers: tourData.pricingTiers
    };
    if (typeof travelers === "number") {
      const tier = priceForTravelers(travelers);
      result.quote = {
        travelers,
        tier: tier.groupSize,
        pricePerPerson: tier.pricePerPerson,
        total: tier.pricePerPerson * travelers
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-inclusions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_inclusions_default = defineTool4({
  name: "get_inclusions",
  title: "Get tour inclusions",
  description: "Return what is included and not included in the East Java 5D4N tour price.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = { included: tourData.included, notIncluded: tourData.notIncluded };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-faq.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.23.8";
var get_faq_default = defineTool5({
  name: "get_faq",
  title: "Get tour FAQ",
  description: "Return frequently asked questions about the East Java tour. Optionally filter by a keyword that must appear in the question or answer.",
  inputSchema: {
    keyword: z2.string().trim().min(1).optional().describe("Optional case-insensitive keyword to filter FAQ entries.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ keyword }) => {
    const kw = keyword?.toLowerCase();
    const faq = kw ? tourData.faq.filter((f) => f.q.toLowerCase().includes(kw) || f.a.toLowerCase().includes(kw)) : tourData.faq;
    return {
      content: [{ type: "text", text: JSON.stringify(faq, null, 2) }],
      structuredContent: { faq }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "east-java-tour-mcp",
  title: "East Java Tour MCP",
  version: "0.1.0",
  instructions: "Public tools for the Java Volcano Tour Operator's 5D4N East Java tour (Ijen, Papuma, Tumpak Sewu, Bromo). Use `get_tour_overview` for the top-level summary, `get_itinerary` for the day-by-day plan, `get_pricing` for per-person tier pricing and quotes by group size, `get_inclusions` for what is included / excluded, and `get_faq` for frequently asked questions.",
  tools: [get_tour_overview_default, get_itinerary_default, get_pricing_default, get_inclusions_default, get_faq_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
